### PR TITLE
Fix positioning bug in Avatar component

### PR DESCRIPTION
**Pull request by bondparkerbond**
Bugfix where Avatar components using text/icons were positioned differently than ones using Images

### CODE REVIEW

**Comment by bondparkerbond** [comment]
Old behavior: 
simulator screen shot nov 11 2016 2 53 45 pm

**Comment by bondparkerbond** [comment]
Old Behavior:
screen shot 2016-11-11 at 2 45 21 pm

**Comment by bondparkerbond** [comment]
New Behavior: 
screen shot 2016-11-11 at 3 16 40 pm

**Comment by TheDirtyCalvinist** [comment]
LGTM

**Pull request merged**
